services:

  db:
    image: postgres:17.2
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "mydb" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  builder:
    build:
      context: .
    user: "1000:1000"
    ports:
      - "5555:5555"
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    working_dir: /usr/src/app
    entrypoint: /bin/sh
    command: -c "npm i && npx prisma db push --force-reset && npx prisma db seed"

  app:
    build:
      context: .
    user: "1000:1000"
    restart: always
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      builder:
        condition: service_completed_successfully
    env_file:
      - .env
    entrypoint: 'npm'
    command: 'run start:dev'
